Neste caso o management host eh esse aqui: se nao for, alterar o ip management host aqui!
Monitoramento iniciado: host 172.16.1.30!
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 1514
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 2962
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 4410
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 1514
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 2962
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 1514
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 2962
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 2962
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 2962
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 2962
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 2962
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 2962
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 2962
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 2962
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 2962
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 2962
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 4410
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 4410
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 1514
4_6_172.16.2.30_172.16.1.30_40872_5001 1745347377 1514
enviando monitoring tempo:  1745347377895
Enviando flowmonitoring para %s:%d 172.16.1.30 9090
Enviando msg_str para -> 172.16.1.30:9090

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nnmoc/host1/host/host_traffic_monitoring/monitoring_utils.py", line 33, in enviar_msg
    tcp.connect((server_ip, server_port))
OSError: [Errno 101] Network is unreachable
